"""
Database of major Indian government schemes with simplified eligibility criteria.

Eligibility values of None/False mean "no restriction on this field".
This is a simplified screening tool, not an official eligibility confirmation --
users are always pointed to the official portal to verify and apply.
"""

SCHEMES = [
    {
        "id": "pm-kisan",
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "category": "Agriculture",
        "description": "Income support of Rs 6,000 per year to landholding farmer families, paid in three installments.",
        "apply_url": "https://pmkisan.gov.in",
        "criteria": {"min_age": 18, "occupations": ["farmer"]},
    },
    {
        "id": "ayushman-bharat",
        "name": "Ayushman Bharat (PM-JAY)",
        "category": "Health",
        "description": "Health cover of Rs 5 lakh per family per year for secondary and tertiary hospitalisation, for economically weaker families.",
        "apply_url": "https://pmjay.gov.in",
        "criteria": {"requires_bpl": True},
    },
    {
        "id": "pmay-urban",
        "name": "Pradhan Mantri Awas Yojana (Urban)",
        "category": "Housing",
        "description": "Financial assistance / interest subsidy for construction or purchase of a house for eligible urban families without a pucca house.",
        "apply_url": "https://pmaymis.gov.in",
        "criteria": {"requires_no_house": True, "max_income": 1800000, "states_type": "urban"},
    },
    {
        "id": "pmay-gramin",
        "name": "Pradhan Mantri Awas Yojana (Gramin)",
        "category": "Housing",
        "description": "Financial assistance to rural, BPL households without a pucca house to construct one.",
        "apply_url": "https://pmayg.nic.in",
        "criteria": {"requires_no_house": True, "requires_bpl": True, "states_type": "rural"},
    },
    {
        "id": "sukanya-samriddhi",
        "name": "Sukanya Samriddhi Yojana",
        "category": "Savings / Girl Child",
        "description": "High-interest savings scheme for the education and marriage expenses of a girl child below 10 years.",
        "apply_url": "https://www.india.gov.in/spotlight/sukanya-samriddhi-yojana",
        "criteria": {"requires_daughter_under_10": True},
    },
    {
        "id": "atal-pension-yojana",
        "name": "Atal Pension Yojana",
        "category": "Pension",
        "description": "Guaranteed monthly pension (Rs 1,000-5,000) after age 60 for workers in the unorganised sector.",
        "apply_url": "https://www.npscra.nsdl.co.in/scheme-details.php",
        "criteria": {"min_age": 18, "max_age": 40, "occupations": ["self_employed", "daily_wage", "unemployed", "farmer", "homemaker"]},
    },
    {
        "id": "pm-ujjwala",
        "name": "PM Ujjwala Yojana",
        "category": "Household / Women",
        "description": "Free LPG gas connection to women from BPL households.",
        "apply_url": "https://www.pmuy.gov.in",
        "criteria": {"gender": "female", "requires_bpl": True},
    },
    {
        "id": "national-scholarship",
        "name": "National Scholarship Portal Schemes",
        "category": "Education",
        "description": "Central/state scholarships covering tuition and maintenance for students from low-income families.",
        "apply_url": "https://scholarships.gov.in",
        "criteria": {"requires_student": True, "max_income": 250000},
    },
    {
        "id": "stand-up-india",
        "name": "Stand-Up India",
        "category": "Business / Loans",
        "description": "Bank loans between Rs 10 lakh-1 crore for setting up a greenfield enterprise, for SC/ST and women entrepreneurs.",
        "apply_url": "https://www.standupmitra.in",
        "criteria": {"requires_business_owner": True, "categories": ["sc", "st"], "gender_or_category": "female"},
    },
    {
        "id": "pmegp",
        "name": "Prime Minister's Employment Generation Programme (PMEGP)",
        "category": "Business / Loans",
        "description": "Credit-linked subsidy for setting up new micro-enterprises to generate self-employment.",
        "apply_url": "https://www.kviconline.gov.in/pmegpeportal",
        "criteria": {"min_age": 18, "requires_business_owner": True},
    },
    {
        "id": "pm-sym",
        "name": "Pradhan Mantri Shram Yogi Maandhan (PM-SYM)",
        "category": "Pension",
        "description": "Voluntary pension scheme for unorganised sector workers with monthly income up to Rs 15,000.",
        "apply_url": "https://maandhan.in/shramyogi",
        "criteria": {"min_age": 18, "max_age": 40, "max_income": 180000, "occupations": ["daily_wage", "self_employed", "unemployed"]},
    },
    {
        "id": "old-age-pension",
        "name": "National Old Age Pension Scheme (IGNOAPS)",
        "category": "Pension",
        "description": "Monthly pension for senior citizens from BPL households.",
        "apply_url": "https://nsap.nic.in",
        "criteria": {"requires_senior": True, "requires_bpl": True},
    },
    {
        "id": "widow-pension",
        "name": "National Family Benefit / Widow Pension Scheme",
        "category": "Pension",
        "description": "Monthly pension support for widows from BPL households aged 40-79.",
        "apply_url": "https://nsap.nic.in",
        "criteria": {"gender": "female", "requires_widow": True, "requires_bpl": True, "min_age": 40, "max_age": 79},
    },
    {
        "id": "disability-pension",
        "name": "National Disability Pension Scheme",
        "category": "Pension / Disability",
        "description": "Monthly pension for persons with severe disabilities from BPL households.",
        "apply_url": "https://nsap.nic.in",
        "criteria": {"requires_disabled": True, "requires_bpl": True, "min_age": 18, "max_age": 79},
    },
    {
        "id": "pm-vishwakarma",
        "name": "PM Vishwakarma Yojana",
        "category": "Business / Skill",
        "description": "Financial support, skill training and toolkit incentive for traditional artisans and craftspeople.",
        "apply_url": "https://pmvishwakarma.gov.in",
        "criteria": {"min_age": 18, "occupations": ["self_employed"]},
    },
    {
        "id": "kisan-credit-card",
        "name": "Kisan Credit Card (KCC)",
        "category": "Agriculture / Loans",
        "description": "Short-term credit at low interest rates for farmers to cover cultivation and other needs.",
        "apply_url": "https://www.myscheme.gov.in/schemes/kcc",
        "criteria": {"occupations": ["farmer"]},
    },
    {
        "id": "pm-matru-vandana",
        "name": "PM Matru Vandana Yojana (PMMVY)",
        "category": "Health / Women",
        "description": "Cash incentive of Rs 5,000 to pregnant women and lactating mothers for their first living child.",
        "apply_url": "https://pmmvy.wcd.gov.in",
        "criteria": {"gender": "female", "min_age": 18, "max_age": 45},
    },
    {
        "id": "mudra-yojana",
        "name": "Pradhan Mantri Mudra Yojana (PMMY)",
        "category": "Business / Loans",
        "description": "Collateral-free loans up to Rs 10 lakh for non-corporate, non-farm micro and small enterprises.",
        "apply_url": "https://www.mudra.org.in",
        "criteria": {"min_age": 18, "requires_business_owner": True},
    },
]
